version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    network_mode: bridge
    volumes:
      - /mnt/zfs/nfs/applications/filebrowser/volumes/srv:/srv
      - /mnt/zfs/nfs/applications/filebrowser/volumes/database:/database
      - /mnt/zfs/nfs/applications/filebrowser/volumes/config:/config
    ports:
      - 8083:80
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0