version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - /home/joe/Public/docker/filebrowser/volumes/srv:/srv
      - /home/joe/Public/docker/filebrowser/volumes/database.db:/database.db
      - /home/joe/Public/docker/filebrowser/volumes/.filebrowser.json:/.filebrowser.json
    ports:
      - 8083:80
    restart: unless-stopped