version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    network_mode: bridge
    volumes:
      - /home/joe/Public/docker/filebrowser/volumes/srv:/srv
      - /home/joe/Public/docker/filebrowser/volumes/database:/database
      - /home/joe/Public/docker/filebrowser/volumes/config:/config
    ports:
      - 8083:80
    restart: unless-stopped
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)