services:
  glances:
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "61208-61209:61208-61209"
    environment:
      - TZ=Etc/UTC
      - "GLANCES_OPT=-w"
      - PUID=0
      - PGID=0
