services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: bridge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /mnt/zfs/nfs/applications/prowlarr/volumes/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped