services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /home/joe/Public/docker/prowlarr/volumes/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped