---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: bridge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${plexclaim}
    volumes:
      - /home/joe/Public/docker/plex/volumes/config:/config
      - /home/joe/Public/docker/qbittorrent-nox/volumes/media/tv:/tv
      - /home/joe/Public/docker/qbittorrent-nox/volumes/media/movies:/movies
    restart: unless-stopped