---
services:
  plex:
    image: lscr.io/linuxserver/lscr.io:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${plexclaim}
    volumes:
      - /home/joe/Public/docker/plex/volumes/config:/config
      - /home/joe/Public/docker/plex/volumes/tv:/tv
      - /home/joe/Public/docker/plex/volumes/movies:/movies
    restart: unless-stopped