volumes:
  postgres_data:
      driver: local

services:
  # postgres-new:
  #     image: postgres
  #     ports:
  #       #make sure you aren't colliding ports with other containers
  #       - "5434:5432"
  #     volumes:
  #       - /home/joe/Public/docker/keycloak/volumes/postgres17:/var/lib/postgresql/data
  #     environment:
  #       POSTGRES_DB: ${pgdb}
  #       POSTGRES_USER: ${pgdb}
  #       POSTGRES_PASSWORD: ${pgpassword}
  #     restart: unless-stopped
  postgres:
      image: postgres:16
      ports:
        #make sure you aren't colliding ports with other containers
        - "5433:5432"
      volumes:
        - /home/joe/Public/docker/keycloak/volumes/postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${pgdb}
        POSTGRES_USER: ${pgdb}
        POSTGRES_PASSWORD: ${pgpassword}
      restart: unless-stopped
  auth:
    image: quay.io/keycloak/keycloak
    ports:
      - "8082:8080"
    restart: unless-stopped
    environment:
      KC_DB: postgres
      DB_DATABASE: ${pgdb}
      KC_DB_USERNAME: ${pgdb}
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: ${pgpassword}
      KC_DB_URL: jdbc:postgresql://postgres/${pgdb}
      KEYCLOAK_ADMIN: ${admin}
      KEYCLOAK_ADMIN_PASSWORD: ${password}
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
    command:
      - start
    depends_on:
      - postgres
      #- postgres-new