services:
  jellyfin:
    image: jellyfin/jellyfin
    network_mode: bridge
    volumes:
      - /home/joe/Public/docker/jellyfin/volumes/config:/config
      - /home/joe/Public/docker/jellyfin/volumes/cache:/cache
      - /home/joe/Public/docker/qbittorrent-nox/volumes/media/tv:/media
      - /home/joe/Public/docker/qbittorrent-nox/volumes/media/movies:/media2
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0