services:
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /home/joe/applications/jellyfin/volumes/config:/config
      - /home/joe/applications/jellyfin/volumes/cache:/cache
      - /mnt/zfs/nfs/applications/qbittorrent-nox/volumes/media/tv:/media
      - /mnt/zfs/nfs/applications/qbittorrent-nox/volumes/media/movies:/media2
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHEDSERVERURL}
    extra_hosts:
      - 'host.docker.internal:host-gateway'