services:
  gluetun:
    image: qmcgaw/gluetun
    network_mode: bridge
    ports:
      - 8080:8080 #qbittorent webUI
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PRIVATEKEY}
      - SERVER_COUNTRIES=United States
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING=on
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ping -c 4 8.8.8.8 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 15s

  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:latest
    container_name: qbittorrent-nox
    environment:
    - PUID=0
    - PGID=0
    - WEBUI_PORT=8080
    read_only: false
    stop_grace_period: 30m
    network_mode: "service:gluetun"
    restart: unless-stopped
    tmpfs:
    - /tmp
    volumes:
    - /home/joe/Public/docker/qbittorrent-nox/volumes/config:/config
    - /home/joe/Public/docker/qbittorrent-nox/volumes/config/gluetun:/config/data_gluetun
    - /home/joe/Public/docker/qbittorrent-nox/volumes/downloads:/downloads
    healthcheck:
      test: ["CMD-SHELL", "ping -c 4 8.8.8.8 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      gluetun:
        condition: service_healthy