services:
  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:latest
    container_name: qbittorrent-nox
    environment:
    - PUID=1004
    - PGID=1001   
    read_only: false
    stop_grace_period: 30m
    tmpfs:
    - /tmp
    volumes:
    - /home/joe/Public/docker/qbittorrent-nox/volumes/config:/config
    - /home/joe/Public/docker/qbittorrent-nox/volumes/config/gluetun:/config/data_gluetun
    - /home/joe/Public/docker/qbittorrent-nox/volumes/downloads:/mnt/downloads
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"