apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-tls
spec:
  secretName: example-tls
  commonName: example.com
  dnsNames:
    - example.com
    - www.example.com
  issuerRef:
    name: ad-ca-issuer
    kind: ClusterIssuer