apiVersion: apps/v1
metadata:
  name: prowlarr
kind: Deployment
spec:
  selector:
    matchLabels:
      tag: prowlarr
  template:
    metadata:
      labels:
        tag: prowlarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "0"
            - name: PUID
              value: "0"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/prowlarr:latest
          name: prowlarr
          ports:
            - containerPort: 9696
              protocol: TCP
      restartPolicy: Always
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 15
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"    
          effect: "NoExecute"    
          tolerationSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  ports:
    - port: 9696
      targetPort: 9696
  selector:
    tag: prowlarr
  type: LoadBalancer
  