apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipallowlist-internal
  namespace: kube-system
spec:
  ipAllowList:
    sourceRange:
      - 127.0.0.1/32
      - 192.168.1.0/24
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: skipverify
  namespace: kube-system
spec:
  insecureSkipVerify: true
---
#traefik dashboard access
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  routes:
  - match: Host(`traefik.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
---
# Redirect to https
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: kube-system
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    # https://github.com/Haxxnet/Compose-Examples/blob/main/examples/traefik/fileConfig.yml
    customResponseHeaders:
      Server: "" # prevent version disclosure
      X-Powered-By: "" # prevent version disclosure
      X-Forwarded-Proto: "https"
    sslProxyHeaders:
      X-Forwarded-Proto: "https"
    hostsProxyHeaders:
      - "X-Forwarded-Host"
    contentTypeNosniff: true
    customFrameOptionsValue: "SAMEORIGIN"
    browserXssFilter: false # X-XSS-Protection; deprecated
    referrerPolicy: "strict-origin-when-cross-origin" # Referrer-Policy
    forceSTSHeader: true # HTTP-Strict-Transport-Security (HSTS)
    stsIncludeSubdomains: true # HTTP-Strict-Transport-Security (HSTS)
    stsSeconds: 63072000 # HTTP-Strict-Transport-Security (HSTS)
    stsPreload: true # HTTP-Strict-Transport-Security (HSTS)    
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: kube-system   # adjust if you use another namespace
spec:
  redirectScheme:
    scheme: https
    permanent: true