global:
  ingressShim:
    defaultIssuerName: ad-ca-issuer
    defaultIssuerKind: ClusterIssuer
  crds:
    create: true
  podSecurityPolicy:
    enabled: false

certManager:
  installCRDs: true
  version: v1.5.4
  extraArgs: []
  extraEnv: []
  image:
    repository: quay.io/jetstack/cert-manager-controller
    tag: "{{ .Values.certManager.version }}"
    pullPolicy: IfNotPresent
  ingressShim:
    defaultIssuerName: ad-ca-issuer
    defaultIssuerKind: ClusterIssuer
  config:
    issuerTimeout: 5m
    renewBefore: 24h
    disableAutoCertificateInjection: false

adCAIssuer:
  name: ad-ca-issuer
  namespace: cert-manager
  caSecretName: ad-ca-secret
  username: username
  password: password
  crlDistributionPoints:
    - http://crl.example.com/ca.crl
  ocspServers:
    - http://ocsp.example.com

exampleTLS:
  name: example-tls
  namespace: default
  commonName: example.com
  dnsNames:
    - example.com
    - www.example.com
  issuerRef:
    name: ad-ca-issuer
    kind: ClusterIssuer

infoblox:
  username: <Infoblox API username>
  password: <Infoblox API password>
  server: <Infoblox server IP or hostname>

acme:
  email: <your email address>
  server: https://acme-v02.api.letsencrypt.org/directory
  webhook:
    groupName: cert-manager.example.com
    solverName: infoblox-webhook