apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          env:
          - name: JELLYFIN_PUBLISHEDSERVERURL
            valueFrom:
              secretKeyRef:
                name: jellyfin-secret
                key: JELLYFIN_PUBLISHEDSERVERURL
          - name: JELLYFIN_IP
            valueFrom:
              secretKeyRef:
                name: jellyfin-secret
                key: JELLYFIN_IP                
          ports:
            - containerPort: 8096
          securityContext:
            privileged: true # Needed for GPU access
          volumeMounts:
            - mountPath: /config
              name: nfs
              subPath: applications/jellyfin/volumes/config
            - mountPath: /cache
              name: nfs
              subPath: applications/jellyfin/volumes/cache
            - mountPath: /media
              name: nfs
              subPath: applications/qbittorrent-nox/volumes/media/tv
            - mountPath: /media2
              name: nfs
              subPath: applications/qbittorrent-nox/volumes/media/movies          
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: truenas-pvc
      restartPolicy: Always
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 15
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"    
          effect: "NoExecute"    
          tolerationSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc-tcp
  annotations:
    metallb.io/address-pool: metallbaddresspool
    metallb.io/allow-shared-ip: "shared-ip"
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc-udp
  annotations:
    metallb.io/address-pool: metallbaddresspool
    metallb.io/allow-shared-ip: "shared-ip"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.248
  selector:
    app: jellyfin
  ports:
    - name: discovery
      port: 7359
      targetPort: 7359
      protocol: UDP