#after installing NGINX using install-nginx.sh - run this to configure NGINX to route requests to your web service over the given port and TLS secret
apiVersion: v1
kind: Secret
metadata:
  name: $TLSSECRETNAME
  namespace: $NAMESPACE
data:
  tls.crt: $BASE64CRT
  tls.key: $BASE64KEY
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $INGRESSNAME
  namespace: $NAMESPACE
spec:
  ingressClassName: nginx
  rules:
    - host: $DNSNAME
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: $SERVICENAME
              port:
                number: 80

  tls:
    - hosts:
      - $DNSNAME
      secretName: $TLSSECRETNAME