services:
  radarr:
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /home/joe/Public/docker/radarr/volumes/config:/config
      - /home/joe/Public/docker/qbittorrent-nox/volumes/:/data
    restart: unless-stopped