services:
  radarr:
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/joe/Public/docker/radarr/volumes/config:/config
      - /home/joe/Public/docker/radarr/volumes/data:/data