services:
  radarr:
    image: ghcr.io/hotio/radarr
    network_mode: bridge
    ports:
      - "7878:7878"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /mnt/zfs/nfs/applications/radarr/volumes/config:/config
      - /mnt/zfs/nfs/applications/qbittorrent-nox/volumes/:/data
    restart: unless-stopped