version: "3.8"
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3022:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMAHOST}
      - CORS_ALLOW_ORIGIN=${CORSDOMAINS}
    volumes:
      - /home/joe/Public/docker/openwebui/volumes:/app/backend/data
    restart: "always"