apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

secretGenerator:
  - name: nginx-proxy-manager-secret
    envs:
      - env-vars.env

generatorOptions:
  disableNameSuffixHash: true