services:
  influxdb:
    image: "influxdb:latest"
    container_name: influxdb
    hostname: influxdb
    mem_limit: 5gb
    ports:
      - "2003:2003"
      - "8086:8086"
    environment:
      TZ: "America/New_York"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
      INFLUXDB_DB: ${INFLUXDB_DB}
    volumes:
      - /home/joe/Public/docker/influxdb/volumes/influxdb:/var/lib/influxdb
    logging:
      driver: "json-file"
      options:
        max-size: "100M"