services:
  prometheus:
    image: prom/prometheus
    network_mode: bridge
    ports:
      - 9090:9090
    volumes:
      - /home/joe/Public/docker/prometheus/volumes/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped