# https://medium.com/@christoph_40852/setting-up-hashicorp-vault-for-easy-development-in-a-docker-environment-41dc1b09d645
services:
  vault:
    image: hashicorp/vault:latest
    network_mode: bridge
    environment:
      VAULT_API_ADDR: ${VAULT_API_ADDR}
      # VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_OIDC_CLIENT_SECRET: ${VAULT_OIDC_CLIENT_SECRET}
      VAULT_OIDC_CLIENT_ID: ${VAULT_OIDC_CLIENT_ID}
      VAULT_OIDC_DISCOVERY_URL: ${VAULT_OIDC_DISCOVERY_URL}
      VAULT_OIDC_REDIRECT_URI: ${VAULT_OIDC_REDIRECT_URI}
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    volumes:
      # - certs will be here /home/joe/Public/docker/nginx-proxy-manager/volumes/letsencrypt/live/npm-25:/opt/vault/tls/
      # will need some job to rename the certs to vault.crt and vault-cert.pem, vault-ca.pem, and vault-key.pem
      - /mnt/zfs/nfs/applications/hashicorp-vault/docker-entrypoint.sh:/docker-entrypoint.sh
      - /mnt/zfs/nfs/applications/hashicorp-vault/volumes/docker-entrypoint-initvault.d/:/docker-entrypoint-initvault.d/
      - /mnt/zfs/nfs/applications/hashicorp-vault/volumes/vault/:/vault/file/
      - /mnt/zfs/nfs/applications/hashicorp-vault/config.hcl:/vault/config/config.hcl
    entrypoint: ["/docker-entrypoint.sh"]

# Examples for the environment variables
# VAULT_API_ADDR=http://127.0.0.1:8200
# VAULT_DEV_ROOT_TOKEN_ID=MAKE_THIS_SOME_SECRET_VALUE
# VAULT_OIDC_CLIENT_SECRET=my-oidc-client-secret
# VAULT_OIDC_CLIENT_ID=my-oidc-client-id
# VAULT_OIDC_DISCOVERY_URL=https://example.com/.well-known/openid-configuration
# VAULT_OIDC_REDIRECT_URI=http://127.0.0.1:8250/oidc/callback or https://yourvault.domain.com/ui/vault/auth/oidc/oidc/callback

# put a .sh script in the docker-entrypoint-initvault.d folder
# make it executable with chmos a+x
# add secrets like so:
  # #!/bin/sh
  # vault secrets enable -path=secret kv
  # vault kv put secret/db_password password="supersecret"