services:
  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_API_ADDR: ${VAULT_API_ADDR}
      VAULT_OIDC_CLIENT_SECRET: ${VAULT_OIDC_CLIENT_SECRET}
      VAULT_OIDC_CLIENT_ID: ${VAULT_OIDC_CLIENT_ID}
      VAULT_OIDC_DISCOVERY_URL: ${VAULT_OIDC_DISCOVERY_URL}
      VAULT_OIDC_REDIRECT_URI: ${VAULT_OIDC_REDIRECT_URI}
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    volumes:
      - /home/joe/Public/docker/hashicorp-vault/docker-entrypoint.sh:/docker-entrypoint.sh
      - /home/joe/Public/docker/hashicorp-vault/volumes/docker-entrypoint-initvault.d/:/docker-entrypoint-initvault.d/
      - /home/joe/Public/docker/hashicorp-vault/volumes/vault/:/vault/file/
      - /home/joe/Public/docker/hashicorp-vault/config.hcl:/vault/config/config.hcl
    entrypoint: ["/docker-entrypoint.sh"]

# Examples for the environment variables
# VAULT_API_ADDR=http://127.0.0.1:8200
# VAULT_DEV_ROOT_TOKEN_ID=MAKE_THIS_SOME_SECRET_VALUE
# VAULT_OIDC_CLIENT_SECRET=my-oidc-client-secret
# VAULT_OIDC_CLIENT_ID=my-oidc-client-id
# VAULT_OIDC_DISCOVERY_URL=https://example.com/.well-known/openid-configuration
# VAULT_OIDC_REDIRECT_URI=http://127.0.0.1:8250/oidc/callback or https://yourvault.domain.com/ui/vault/auth/oidc/oidc/callback