# https://medium.com/@christoph_40852/setting-up-hashicorp-vault-for-easy-development-in-a-docker-environment-41dc1b09d645
services:
  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_API_ADDR: ${VAULT_API_ADDR}
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_OIDC_CLIENT_SECRET: ${VAULT_OIDC_CLIENT_SECRET}
      VAULT_OIDC_CLIENT_ID: ${VAULT_OIDC_CLIENT_ID}
      VAULT_OIDC_DISCOVERY_URL: ${VAULT_OIDC_DISCOVERY_URL}
      VAULT_OIDC_REDIRECT_URI: ${VAULT_OIDC_REDIRECT_URI}
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    volumes:
      - /home/joe/Public/docker/hashicorp-vault/docker-entrypoint.sh:/docker-entrypoint.sh
      - /home/joe/Public/docker/hashicorp-vault/volumes/docker-entrypoint-initvault.d/:/docker-entrypoint-initvault.d/
    entrypoint: "/docker-entrypoint.sh"
    command: ["server", "-dev"]

# put a .sh script in the docker-entrypoint-initvault.d folder
# make it executable with chmos a+x
# add secrets like so:
  # #!/bin/sh
  # vault secrets enable -path=secret kv
  # vault kv put secret/db_password password="supersecret"