services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    command: --config /oauth2-proxy.cfg
    environment:
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
    ports:
      - 4180:4180/tcp
    volumes:
      - /home/joe/Public/docker/oauth2proxy/volumes/oauth2-proxy.cfg:/oauth2-proxy.cfg
    restart: unless-stopped