version: '3'
services:
  rundeck:
    image: rundeck/rundeck:4.4.0
    network_mode: bridge
    restart: unless-stopped
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: rundeck
      RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
      RUNDECK_STORAGE_CONVERTER_1_CONFIG_PASSWORD: rundeck
      RUNDECK_CONFIG_STORAGE_CONVERTER_1_CONFIG_PASSWORD: rundeck
      RUNDECK_GRAILS_URL: ${RUNDECK_GRAILS_URL}
      RUNDECK_SERVER_FORWARDED: 'true'
    ports:
      - '4440:4440'
  mysql:
    image: mysql:5.7
    network_mode: bridge
    restart: unless-stopped
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}